// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBcNafIwVHqO6p8TCxNQIhzWyzQozJUqY',
    appId: '1:235586402217:web:17f286e3375cb232dd76b8',
    messagingSenderId: '235586402217',
    projectId: 'anime-app-f6bbc',
    authDomain: 'anime-app-f6bbc.firebaseapp.com',
    storageBucket: 'anime-app-f6bbc.firebasestorage.app',
    measurementId: 'G-MC6QFGESB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTp5QYjudGXWvsYdTlbaEYJE6Ge2n7BPo',
    appId: '1:235586402217:android:a319ccb23738a554dd76b8',
    messagingSenderId: '235586402217',
    projectId: 'anime-app-f6bbc',
    storageBucket: 'anime-app-f6bbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7yaSz68C84XrgZ_kaAPPpofttQkcVhac',
    appId: '1:235586402217:ios:cc42d50cfe3d7c1edd76b8',
    messagingSenderId: '235586402217',
    projectId: 'anime-app-f6bbc',
    storageBucket: 'anime-app-f6bbc.firebasestorage.app',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7yaSz68C84XrgZ_kaAPPpofttQkcVhac',
    appId: '1:235586402217:ios:cc42d50cfe3d7c1edd76b8',
    messagingSenderId: '235586402217',
    projectId: 'anime-app-f6bbc',
    storageBucket: 'anime-app-f6bbc.firebasestorage.app',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBcNafIwVHqO6p8TCxNQIhzWyzQozJUqY',
    appId: '1:235586402217:web:4825cc62a2f864fadd76b8',
    messagingSenderId: '235586402217',
    projectId: 'anime-app-f6bbc',
    authDomain: 'anime-app-f6bbc.firebaseapp.com',
    storageBucket: 'anime-app-f6bbc.firebasestorage.app',
    measurementId: 'G-5V2199H55V',
  );
}
